pipeline {
    agent any
    
    options {
        skipStagesAfterUnstable()
    }

    stages {
        stage('Checkout'){
            steps{
                // Checkout GitHub Repository
                git branch: 'main', url: 'https://github.com/Prashun08/Flask-App.git'
            }
        }
        stage('Build') {
            steps {
                // Install dependencies (if any)
                withPythonEnv('python3') {
                    sh 'pip3 install -r requirements.txt'
                    sh 'python -m py_compile app.py' 
                    stash(name: 'compiled-results', includes: '*.py*') 
                }
            }
        }
        stage('Test') {
            steps {
                // Run pytest and generate XML report
                withPythonEnv('python3') {
                    sh 'py.test --junit-xml test-reports/results.xml Test/test_app.py'
                }
            }
            post {
                always {
                    junit 'test-reports/results.xml'
                }
            }
        }
        stage('Snyk Vulnerability Checks') {
            steps {
                echo 'Testing...'
                withPythonEnv('python3') {
                    snykSecurity(
                        snykInstallation: 'Snyk',
                        snykTokenId: 'snyk-api',
                        failOnIssues: false,
                        // additionalArguments: '--package-manager=pip3 --file=app.py'
                    )
                }
            }
        }
        stage('Deliver') { 
            steps {
                withPythonEnv('python3') {
                    sh "pyinstaller --onefile app.py" 
                }
            }
        }
        stage('Environment Prompt') {
            steps {
                script {
                    env.DEPLOY_ENV = input message: 'Select the deployment environment:', parameters: [choice(name: 'Environment', choices: ['PROD', 'NON-PROD'], description: 'Deployment Environment')]
                }
            }
        }
        stage('Archive or Deliver') {
            steps {
                script {
                    if (env.DEPLOY_ENV == 'PROD') {
                        sh "mv dist/app dist/app_${env.BUILD_ID}"
                        archiveArtifacts artifacts: "dist/app_${env.BUILD_ID}", allowEmptyArchive: true, fingerprint: true
                        currentBuild.displayName = "#${env.BUILD_ID} - ${env.DEPLOY_ENV}"
                    } else {
                        echo 'Non-Prod deployment, no renaming needed'
                        archiveArtifacts artifacts: 'dist/app', allowEmptyArchive: true, fingerprint: true
                    }
                }
            }
        }
        stage('Slack Notification') {
            steps{
                slackSend(channel: "#python-api-jenkins", message: "Jenkins pipeline ran successfully in ${env.DEPLOY_ENV}. Please check Snyk dashboard for any issues.")
            }
        }
    }
}
